name: "Tests"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: "bash"

env:
  VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json,read"
  VCPKG_ROOT: "${{ github.workspace }}/vcpkg"

permissions:
  contents: "read"
  packages: "read"

jobs:
  TestOnMacOS:
    runs-on: "macos-15"
    timeout-minutes: 30

    steps:
      - name: "Checkout project repository"
        uses: "actions/checkout@v5"

      - name: "Checkout vcpkg repository"
        uses: "actions/checkout@v5"
        with:
          repository: "microsoft/vcpkg"
          path: "${{ env.VCPKG_ROOT }}"

      - name: "Bootstrap vcpkg"
        working-directory: "${{ env.VCPKG_ROOT }}"
        run: "./bootstrap-vcpkg.sh"

      - name: "Install mono for NuGet"
        run: "brew install mono"

      - name: "Setup NuGet Credentials"
        run: |
          NUGET_PATH="$($VCPKG_ROOT/vcpkg fetch nuget | tail -n1)"
          mono "$NUGET_PATH" sources add \
            -Source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            -StorePasswordInClearText \
            -Name "GitHub" \
            -UserName "${{ github.repository_owner }}" \
            -Password "${{ secrets.GITHUB_TOKEN }}"

      - name: "Install dependencies from vcpkg"
        run: ".github/scripts/install-vcpkg-macos.bash"

      - name: "Configure"
        run: "cmake --preset macos-testing-ci"
        
      - name: "Build"
        run: "cmake --build --preset macos-testing-ci"
        
      - name: "Run tests"
        run: "ctest --preset macos-testing-ci --verbose"

  TestOnWindows:
    runs-on: "windows-2022"
    timeout-minutes: 30

    steps:
      - name: "Checkout project repository"
        uses: "actions/checkout@v5"

      - name: "Checkout vcpkg repository"
        uses: "actions/checkout@v5"
        with:
          repository: "microsoft/vcpkg"
          path: "${{ env.VCPKG_ROOT }}"

      - name: "Bootstrap vcpkg"
        working-directory: "${{ env.VCPKG_ROOT }}"
        shell: "pwsh"
        run: ".\\bootstrap-vcpkg.bat"

      - name: "Setup NuGet Credentials on Windows"
        shell: pwsh
        run: |
          $NUGET_EXE_PATH = & "${{ env.VCPKG_ROOT }}/vcpkg" fetch nuget | Select-Object -Last 1
          
          & $NUGET_EXE_PATH sources add `
            -Source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" `
            -StorePasswordInClearText `
            -Name "GitHub" `
            -UserName "${{ github.repository_owner }}" `
            -Password "${{ secrets.GITHUB_TOKEN }}"

      - name: "Install dependencies from vcpkg"
        run: "$VCPKG_ROOT/vcpkg install --triplet x64-windows-static-md"

      - name: "Configure"
        run: "cmake --preset windows-testing-ci-x64"

      - name: "Build"
        run: "cmake --build --preset windows-testing-ci-x64"
        
      - name: "Run tests"
        run: "ctest --preset windows-testing-ci-x64 --verbose"

  TestOnUbuntu:
    runs-on: "ubuntu-24.04"
    timeout-minutes: 30

    steps:
      - name: "Checkout project repository"
        uses: "actions/checkout@v5"

      - name: "Checkout vcpkg repository"
        uses: "actions/checkout@v5"
        with:
          repository: "microsoft/vcpkg"
          path: "${{ env.VCPKG_ROOT }}"

      - name: "Bootstrap vcpkg"
        working-directory: "${{ env.VCPKG_ROOT }}"
        run: "./bootstrap-vcpkg.sh"

      - name: "Install system dependencies on Ubuntu"
        run: |
          echo "man-db man-db/auto-update boolean false" | sudo debconf-set-selections
          sudo apt-get remove --purge -y man-db
          sudo add-apt-repository -y ppa:obsproject/obs-studio
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            libgles2-mesa-dev \
            obs-studio \
            qt6-base-dev \
            libqt6svg6-dev \
            qt6-base-private-dev \
            cmake \
            git \
            jq \
            ninja-build \
            pkg-config \
            mono-devel
            
      - name: "Setup NuGet Credentials"
        run: |
          NUGET_PATH="$($VCPKG_ROOT/vcpkg fetch nuget | tail -n1)"
          mono "$NUGET_PATH" sources add \
            -Source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            -StorePasswordInClearText \
            -Name "GitHub" \
            -UserName "${{ github.repository_owner }}" \
            -Password "${{ secrets.GITHUB_TOKEN }}"

      - name: "Install dependencies from vcpkg"
        run: "$VCPKG_ROOT/vcpkg install --triplet x64-linux"

      - name: "Configure"
        run: "cmake --preset ubuntu-testing-ci-x86_64"

      - name: "Build"
        run: "cmake --build --preset ubuntu-testing-ci-x86_64"
        
      - name: "Run tests"
        run: "ctest --preset ubuntu-testing-ci-x86_64 --verbose"
